### ISSUE TITLE
disable pin from drag

### ISSUE THREAD

**Issue by mattshepherd** [Oomph/MacMapKit#1]
is there a way to disable a pin from being dragged?

**Comment by mattshepherd** [comment]
never mind, figured it out.

**Comment by mattshepherd** [comment]
The pins don't respond to clicks if you disable dragging.

**Comment by rickfillion** [comment]
Yea there's an issue with gmaps with that.  It's on my todo list to look into as I have a screen in Sidekick where I want pins to be selectable but not draggable.

**Comment by rickfillion** [comment]
Try it now.  I think I just fixed it.  Reopen the issue if you're still having problems.

**Comment by mattshepherd** [comment]
thanks, i will try it out soon.
