### ISSUE TITLE
Incompatible with Maverics

### ISSUE THREAD

**Issue by scottsykora** [Oomph/MacMapKit#39]
the mavericks sdk has added it's own mapkit. Unfortunately it's only available for apps that are sold through the app store. I'd love to still be able to use this version of map kit for my non-appstore app. It looks like it would probably just need to be recompiled with a different framework name so it wouldn't conflict with the official api's symbols. 

Are there any plans to add this in the future?

**Comment by gazzer82** [comment]
I would also very much like to see this, the decision from Apple makes using the built-in MapKit a non-starter for me.

Thanks

Gareth

**Comment by brunophilipe** [comment]
Rename all &#60;MapKit/file.h&#62; includes to "file.h" and it should work. Compiling in OS X 10.9.1 with Xcode 5.1-DP2 just fine!
