### ISSUE TITLE
Subtitles in annotations

### ISSUE THREAD

**Issue by skndn60** [Oomph/MacMapKit#9]
Am I correct that subtitles for annotations are not supported?

I do the following:

```
[anAnnotation setCoordinate: [[self mapView] centerCoordinate]];
[anAnnotation setTitle: [[self selectedLocation] name]];
[anAnnotation setSubtitle: @"Some subtitle"];
[[self mapView] addAnnotation:anAnnotation];
```

The annotation shows up ok and when I click the pin only the title is displayed in the call out.

Great work by the way for making this available!

**Comment by gazzer82** [comment]
Can i ask this same question, i know it was quite a long time ago!
